# Generated by Django 6.0.2 on 2026-03-14 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0002_create_default_vault'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaultmembership',
            name='role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('admin', 'Admin')], default='viewer', max_length=20),
        ),
    ]
