# Generated by Django 6.0.2 on 2026-03-14 22:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaults', '0004_migrate_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vault',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vault',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vault',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='VaultAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('vault_created', 'Vault Created'), ('member_added', 'Member Added'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('vault_locked', 'Vault Locked'), ('vault_unlocked', 'Vault Unlocked')], max_length=30)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vault', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to='vaults.vault')),
            ],
            options={
                'db_table': 'vaults_vault_audit_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
