# Generated by Django 6.0.2 on 2026-03-08 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0002_item_current_version_itemversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MailboxArtifact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=300)),
                ('content', models.TextField()),
                ('file_size', models.PositiveIntegerField()),
                ('content_type', models.CharField(default='text/markdown', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mailbox_artifacts', to='items.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailbox_artifacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mailbox_artifact',
                'ordering': ['-created_at'],
            },
        ),
    ]
