# Generated by Django 6.0.2 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailbox', '0002_alter_mailboxartifact_managers_and_more'),
        ('vaults', '0001_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailboxartifact',
            name='vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='mailbox_artifacts', to='vaults.vault'),
        ),
    ]
