# Generated by Django 6.0.2 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_account_status_alter_sitesettings_id_and_more'),
        ('vaults', '0001_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active_vault',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='vaults.vault'),
        ),
    ]
