# Generated by Django 6.0.2 on 2026-03-14 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_site_admin',
            field=models.BooleanField(default=False),
        ),
    ]
