# Generated by Django 6.0.2 on 2026-03-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='ai_api_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_api_url',
            field=models.URLField(blank=True, help_text='Custom base URL for provider API.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_model',
            field=models.CharField(blank=True, help_text='e.g. gpt-4o, claude-sonnet-4-20250514', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='ai_provider_type',
            field=models.CharField(blank=True, choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic')], max_length=20),
        ),
    ]
