# Generated by Django 6.0.2 on 2026-03-22 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sitesettings_ai_api_key_sitesettings_ai_api_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='registration_requires_approval',
            field=models.BooleanField(default=False, help_text='When enabled, newly registered accounts start locked and must be approved by a site admin.'),
        ),
    ]
