# Generated by Django 6.0.2 on 2026-03-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_registration_requires_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='registration_requires_approval',
        ),
    ]
