# Generated by Django 6.0.2 on 2026-03-02 21:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
        ('relations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='source_item_type',
            field=models.ForeignKey(blank=True, help_text='Item type allowed as source. NULL means any type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_relation_types', to='items.itemtype'),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='target_item_type',
            field=models.ForeignKey(blank=True, help_text='Item type allowed as target. NULL means any type.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_relation_types', to='items.itemtype'),
        ),
    ]
