# Generated by Django 6.0.2 on 2026-03-07 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0002_relationtype_source_item_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='is_builtin',
            field=models.BooleanField(default=False, help_text='Built-in relation types cannot be deleted.'),
        ),
    ]
