# Generated by Django 6.0.2 on 2026-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0003_add_is_builtin_to_relationtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtype',
            name='kind',
            field=models.CharField(choices=[('composition', 'Composition'), ('trace', 'Trace')], default='trace', max_length=20),
        ),
    ]
