# Generated by Django 6.0.2 on 2026-03-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0005_populate_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtype',
            name='kind',
            field=models.CharField(choices=[('composition', 'Composition'), ('trace', 'Trace')], max_length=20),
        ),
    ]
