# Generated by Django 6.0.2 on 2026-03-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0006_remove_kind_default'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemrelation',
            options={'ordering': ['position', 'created_at']},
        ),
        migrations.AddField(
            model_name='itemrelation',
            name='position',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
