# Generated by Django 6.0.2 on 2026-03-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0007_add_position_to_itemrelation'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrelation',
            name='source_version',
            field=models.PositiveIntegerField(blank=True, help_text='Pin source to this version number. NULL = latest.', null=True),
        ),
        migrations.AddField(
            model_name='itemrelation',
            name='target_version',
            field=models.PositiveIntegerField(blank=True, help_text='Pin target to this version number. NULL = latest.', null=True),
        ),
    ]
