# Generated by Django 6.0.2 on 2026-03-11 21:04

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_customfielddefinition_managers_and_more'),
        ('relations', '0009_backfill_relation_versions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='itemrelation',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='relationtype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='itemrelation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemrelation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemrelation',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='relationtype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='itemrelation',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_relations', to='items.item'),
        ),
        migrations.AlterField(
            model_name='itemrelation',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='items.item'),
        ),
        migrations.AlterField(
            model_name='relationtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='itemrelation',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('relation_type', 'source', 'target'), name='unique_alive_item_relation'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_alive_relation_type_name'),
        ),
    ]
