# Generated by Django 6.0.2 on 2026-03-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relations', '0010_alter_itemrelation_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrelation',
            name='version_pinned',
            field=models.BooleanField(default=False, help_text='User explicitly reviewed and chose to keep older version reference.'),
        ),
    ]
