# Generated by Django 6.0.2 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_add_vault_fk_nullable'),
        ('relations', '0011_add_version_pinned_to_itemrelation'),
        ('vaults', '0001_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='relationtype',
            name='unique_alive_relation_type_name',
        ),
        migrations.AddField(
            model_name='relationtype',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='relation_types', to='vaults.vault'),
        ),
        migrations.AddConstraint(
            model_name='relationtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vault', 'name'), name='unique_alive_relation_type_name'),
        ),
    ]
