# Generated by Django 6.0.2 on 2026-03-01 21:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('items', '0001_initial'),
        ('relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Matrix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_matrices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matrices_matrix',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MatrixColumn',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('label', models.CharField(max_length=200)),
                ('direction', models.CharField(blank=True, choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=10, null=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columns', to='matrices.matrix')),
                ('relation_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_columns', to='relations.relationtype')),
                ('seed_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_seed_container_columns', to='items.item')),
                ('seed_item_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_seed_columns', to='items.itemtype')),
            ],
            options={
                'db_table': 'matrices_matrix_column',
                'ordering': ['position'],
                'unique_together': {('matrix', 'position')},
            },
        ),
    ]
