# Generated by Django 6.0.2 on 2026-03-11 21:04

import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_customfielddefinition_managers_and_more'),
        ('matrices', '0001_initial'),
        ('relations', '0010_alter_itemrelation_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='matrix',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='matrixcolumn',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='matrixcolumn',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='matrix',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrix',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='matrixcolumn',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='matrixcolumn',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='matrixcolumn',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='columns', to='matrices.matrix'),
        ),
        migrations.AddConstraint(
            model_name='matrixcolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('matrix', 'position'), name='unique_alive_matrix_column_position'),
        ),
    ]
