# Generated by Django 6.0.2 on 2026-03-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0002_alter_matrix_managers_alter_matrixcolumn_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixcolumn',
            name='column_kind',
            field=models.CharField(choices=[('seed', 'Seed'), ('traversal', 'Traversal'), ('formula', 'Formula')], default='traversal', max_length=10),
        ),
        migrations.AddField(
            model_name='matrixcolumn',
            name='formula',
            field=models.TextField(blank=True, default=''),
        ),
    ]
