# Generated by Django 6.0.2 on 2026-03-12 19:49

from django.db import migrations


def backfill_column_kind(apps, schema_editor):
    MatrixColumn = apps.get_model("matrices", "MatrixColumn")
    MatrixColumn.objects.filter(position=0).update(column_kind="seed")
    MatrixColumn.objects.filter(position__gt=0).update(column_kind="traversal")


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0003_add_column_kind_and_formula'),
    ]

    operations = [
        migrations.RunPython(backfill_column_kind, migrations.RunPython.noop),
    ]
