# Generated by Django 6.0.2 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0004_backfill_column_kind'),
        ('vaults', '0001_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='matrix',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrices', to='vaults.vault'),
        ),
    ]
