# Generated by Django 6.0.2 on 2026-03-21 17:15

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrices', '0006_make_vault_fk_nonnull'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matrixcolumn',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='matrixcolumn',
            name='source_column_position',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='matrixcolumn',
            name='column_kind',
            field=models.CharField(choices=[('seed', 'Seed'), ('traversal', 'Traversal'), ('formula', 'Formula'), ('annotation', 'Annotation'), ('item_field', 'Item Field')], default='traversal', max_length=15),
        ),
        migrations.CreateModel(
            name='MatrixAnnotation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_slug', models.SlugField(max_length=100)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matrix', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='annotations', to='matrices.matrix')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_matrix_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matrices_matrix_annotation',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('matrix', 'column_slug', 'row_hash'), name='unique_alive_matrix_annotation')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
