# Generated by Django 6.0.2 on 2026-03-22 10:26

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0008_add_table_field'),
        ('matrices', '0007_add_annotation_item_field_support'),
        ('relations', '0013_make_vault_fk_nonnull'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatrixDisplayColumn',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('heading', models.CharField(max_length=200)),
                ('source_name', models.SlugField(max_length=100)),
            ],
            options={
                'db_table': 'matrices_matrix_display_column',
                'ordering': ['position'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='MatrixSource',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=100)),
                ('position', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('seed', 'Seed'), ('traversal', 'Traversal'), ('formula', 'Formula'), ('annotation', 'Annotation'), ('item_field', 'Item Field')], max_length=15)),
                ('direction', models.CharField(blank=True, choices=[('outgoing', 'Outgoing'), ('incoming', 'Incoming')], max_length=10, null=True)),
                ('formula', models.TextField(blank=True, default='')),
                ('source_ref', models.SlugField(blank=True, default='', help_text='Name of the source whose items to read the field from', max_length=100)),
                ('field_slug', models.SlugField(blank=True, default='', help_text='Custom field slug to display', max_length=100)),
            ],
            options={
                'db_table': 'matrices_matrix_source',
                'ordering': ['position'],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='matrixcolumn',
            name='unique_alive_matrix_column_position',
        ),
        migrations.AddField(
            model_name='matrixdisplaycolumn',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='display_columns', to='matrices.matrix'),
        ),
        migrations.AddField(
            model_name='matrixsource',
            name='matrix',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='matrices.matrix'),
        ),
        migrations.AddField(
            model_name='matrixsource',
            name='relation_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_sources', to='relations.relationtype'),
        ),
        migrations.AddField(
            model_name='matrixsource',
            name='seed_container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matrix_seed_container_sources', to='items.item'),
        ),
        migrations.AddField(
            model_name='matrixsource',
            name='seed_item_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matrix_seed_sources', to='items.itemtype'),
        ),
        migrations.RemoveField(
            model_name='matrixcolumn',
            name='matrix',
        ),
        migrations.RemoveField(
            model_name='matrixcolumn',
            name='relation_type',
        ),
        migrations.RemoveField(
            model_name='matrixcolumn',
            name='seed_container',
        ),
        migrations.RemoveField(
            model_name='matrixcolumn',
            name='seed_item_type',
        ),
        migrations.AddConstraint(
            model_name='matrixdisplaycolumn',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('matrix', 'position'), name='unique_alive_matrix_display_column_position'),
        ),
        migrations.AddConstraint(
            model_name='matrixsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('matrix', 'name'), name='unique_alive_matrix_source_name'),
        ),
        migrations.AddConstraint(
            model_name='matrixsource',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('matrix', 'position'), name='unique_alive_matrix_source_position'),
        ),
        migrations.DeleteModel(
            name='MatrixColumn',
        ),
    ]
