# Generated by Django 6.0.2 on 2026-03-11 21:04

import django.db.models.deletion
import django.db.models.manager
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_item_current_version_itemversion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customfielddefinition',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='customfieldvalue',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='item',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemtype',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='itemversion',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='customfielddefinition',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='customfieldvalue',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='itemversion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfielddefinition',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customfieldvalue',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemtype',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='itemversion',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemversion',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='customfielddefinition',
            name='item_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_fields', to='items.itemtype'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='field_definition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='items.customfielddefinition'),
        ),
        migrations.AlterField(
            model_name='customfieldvalue',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='custom_field_values', to='items.item'),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemtype',
            name='slug',
            field=models.SlugField(max_length=100),
        ),
        migrations.AlterField(
            model_name='itemversion',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='items.item'),
        ),
        migrations.AddConstraint(
            model_name='customfielddefinition',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('item_type', 'slug'), name='unique_alive_custom_field_def_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='customfieldvalue',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('item', 'field_definition'), name='unique_alive_custom_field_value_item_def'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('name',), name='unique_alive_item_type_name'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('slug',), name='unique_alive_item_type_slug'),
        ),
        migrations.AddConstraint(
            model_name='itemversion',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('item', 'version_number'), name='unique_alive_item_version_number'),
        ),
    ]
