# Generated by Django 6.0.2 on 2026-03-14 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_document_template'),
        ('vaults', '0001_add_vault_fk_nullable'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='itemtype',
            name='unique_alive_item_type_name',
        ),
        migrations.RemoveConstraint(
            model_name='itemtype',
            name='unique_alive_item_type_slug',
        ),
        migrations.AddField(
            model_name='itemtype',
            name='vault',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='item_types', to='vaults.vault'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vault', 'name'), name='unique_alive_item_type_name'),
        ),
        migrations.AddConstraint(
            model_name='itemtype',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('vault', 'slug'), name='unique_alive_item_type_slug'),
        ),
    ]
