# Generated by Django 6.0.2 on 2026-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_make_vault_fk_nonnull'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_kind',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('choice', 'Choice'), ('mermaid', 'Mermaid')], max_length=20),
        ),
    ]
