# Generated by Django 6.0.2 on 2026-03-21 21:22

import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_customfielddefinition_field_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='field_kind',
            field=models.CharField(choices=[('text', 'Text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('choice', 'Choice'), ('mermaid', 'Mermaid'), ('table', 'Table')], max_length=20),
        ),
        migrations.CreateModel(
            name='ItemTableAnnotation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('column_slug', models.SlugField(max_length=100)),
                ('row_hash', models.CharField(db_index=True, max_length=64)),
                ('value', models.TextField(blank=True, default='')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_definition', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_annotations', to='items.customfielddefinition')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='table_annotations', to='items.item')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='updated_item_table_annotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'items_item_table_annotation',
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('item', 'field_definition', 'column_slug', 'row_hash'), name='unique_alive_item_table_annotation')],
            },
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('all_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
